version: "3.8"

services:
  app:
    build: . # uses current directory's Dockerfile
    # image: url-shortener:latest # => optional dockerfile or image, choose 1
    ports:
      - "5000:5000" # Host:Container
    volumes:
      - .:/code
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
# command - docker-compose up --build
# Go inside the mongo container and run command `mongosh` and then `show dbs` to see the databases
